"""Genera las figuras maestras del paper.

  F1 (TODO LaTeX) - pipeline diagram, mejor hacerla en dibujo
  F2 - espectrogramas comparados de 4 variantes de rolling_droplet
  F3 - heatmap de monotonicidad |rho| por (escena, knob, metric)
  F4 - sweep monotonia: knob_value vs metric para escenas seleccionadas
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import soundfile as sf

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# Estilo paper: tipografia serif legible, tamano consistente
plt.rcParams.update({
    "font.family": "serif",
    "font.size": 11,
    "axes.titlesize": 12,
    "axes.labelsize": 11,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "legend.fontsize": 10,
    "figure.dpi": 140,
    "savefig.bbox": "tight",
    "axes.grid": True,
    "grid.alpha": 0.25,
})

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from impossible_mix.config import SAMPLE_RATE

FIG_DIR = Path("figures")
FIG_DIR.mkdir(exist_ok=True, parents=True)


def fig2_spectrograms() -> None:
    """Espectrogramas comparados de 4 variantes del rolling droplet."""
    variants = [("canonical", "(a) canonical"),
                ("very_wet",  "(b) very wet"),
                ("slow_roll", "(c) slow roll"),
                ("fast_roll", "(d) fast roll")]
    fig, axes = plt.subplots(1, 4, figsize=(15, 3.6), sharey=True)
    im = None
    for ax, (name, title) in zip(axes, variants):
        path = Path(f"perceptual_test/stimuli/A_rolling_droplet__{name}.wav")
        y, sr = sf.read(str(path), dtype="float32", always_2d=False)
        if y.ndim == 2:
            y = y.mean(axis=1)
        from scipy.signal import stft
        f, t, Z = stft(y, fs=sr, nperseg=1024, noverlap=512)
        S_db = 20 * np.log10(np.abs(Z) + 1e-9)
        im = ax.pcolormesh(t, f / 1000.0, S_db, vmin=-80, vmax=-10, cmap="magma", shading="auto")
        ax.set_title(title)
        ax.set_xlabel("Time (s)")
        ax.set_ylim(0, 8)
        ax.grid(False)
    axes[0].set_ylabel("Frequency (kHz)")
    cb = fig.colorbar(im, ax=axes, shrink=0.85, pad=0.01, label="Magnitude (dB)")
    fig.suptitle("Fig. 2. Spectrograms of four rolling-droplet variants generated by the parametric framework",
                 fontsize=12, y=1.04)
    fig.savefig(FIG_DIR / "F2_rolling_droplet_spectrograms.png")
    plt.close(fig)
    print(f"Saved {FIG_DIR/'F2_rolling_droplet_spectrograms.png'}")


def fig3_monotonicity_heatmap() -> None:
    """Heatmap: |rho_max| por (escena, knob)."""
    df = pd.read_csv("results/monotonicity/summary.csv")
    df["abs_rho"] = df["spearman_rho"].abs()
    # max sobre metricas por (scene, knob)
    pivot = (df.groupby(["scene", "knob"])["abs_rho"].max()
             .unstack("knob")
             .reindex(index=["A_rolling_droplet", "B_liquid_rock_impact", "C_wet_gravel_scrape"])
             .reindex(columns=["wetness", "granularity", "rigidity", "resonance", "continuity"]))

    fig, ax = plt.subplots(figsize=(8, 3.2))
    im = ax.imshow(pivot.values, cmap="viridis", vmin=0, vmax=1, aspect="auto")
    ax.set_xticks(range(pivot.shape[1]))
    ax.set_xticklabels(pivot.columns)
    ax.set_yticks(range(pivot.shape[0]))
    ax.set_yticklabels([i.replace("A_", "(A) ").replace("B_", "(B) ").replace("C_", "(C) ").replace("_", " ")
                        for i in pivot.index])
    for i in range(pivot.shape[0]):
        for j in range(pivot.shape[1]):
            v = pivot.values[i, j]
            if np.isnan(v):
                ax.text(j, i, "-", ha="center", va="center", color="gray", fontsize=11)
            else:
                ax.text(j, i, f"{v:.2f}", ha="center", va="center",
                        color="white" if v < 0.5 else "black", fontsize=10)
    cb = fig.colorbar(im, ax=ax, shrink=0.85, pad=0.02)
    cb.set_label(r"$\max_{\rm metric}\, |\rho_{\rm Spearman}|$")
    ax.grid(False)
    ax.set_title(r"Fig. 3. Monotonicity of physical knobs: 10 of 15 (scene, knob) pairs reach $|\rho|>0.7$",
                 fontsize=11)
    fig.tight_layout()
    fig.savefig(FIG_DIR / "F3_monotonicity_heatmap.png")
    plt.close(fig)
    print(f"Saved {FIG_DIR/'F3_monotonicity_heatmap.png'}")


def fig4_sweep_curves() -> None:
    """Curvas monotonia: dyn_db vs knob_value para los knobs mas claros."""
    # Pares (escena, knob) con monotonia fuerte
    targets = [
        ("A_rolling_droplet", "continuity"),
        ("A_rolling_droplet", "wetness"),
        ("B_liquid_rock_impact", "resonance"),
        ("C_wet_gravel_scrape", "continuity"),
        ("C_wet_gravel_scrape", "wetness"),
    ]
    titles = ["(a) A · continuity", "(b) A · wetness",
              "(c) B · resonance", "(d) C · continuity", "(e) C · wetness"]
    fig, axes = plt.subplots(1, 5, figsize=(18, 3.2), sharey=False)
    for ax, (scene, knob), title in zip(axes, targets, titles):
        df = pd.read_csv(f"results/monotonicity/{scene}__{knob}__metrics.csv")
        ax.plot(df["knob_value"], df["dyn_db"], "o-", color="#1565c0", lw=1.8, ms=6, label="dyn (dB)")
        ax2 = ax.twinx()
        ax2.plot(df["knob_value"], df["centroid_hz"] / 1000.0, "s--", color="#c62828", lw=1.5, ms=5, label="centroid (kHz)")
        ax.set_xlabel(f"{knob} knob value")
        ax.set_title(title)
        ax.set_ylabel("dyn range (dB)", color="#1565c0")
        ax2.set_ylabel("centroid (kHz)", color="#c62828")
        ax.tick_params(axis="y", labelcolor="#1565c0")
        ax2.tick_params(axis="y", labelcolor="#c62828")
        ax2.grid(False)
    fig.suptitle("Fig. 4. Five monotonic sweeps; each physical knob produces an audible, ordered effect",
                 fontsize=12, y=1.02)
    fig.tight_layout()
    fig.savefig(FIG_DIR / "F4_sweep_curves.png")
    plt.close(fig)
    print(f"Saved {FIG_DIR/'F4_sweep_curves.png'}")


def main() -> int:
    fig2_spectrograms()
    fig3_monotonicity_heatmap()
    fig4_sweep_curves()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
